server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: mochi
  datasource:
    url: jdbc:postgresql://localhost:5432/mochi
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG